### PR TITLE
Add python dependency so remote build will work

### PR DESCRIPTION
**Pull request by joshuaauerbachwatson**
The title says it all.

### CODE REVIEW

**Comment by joshuaauerbachwatson** [comment]
I notice there was a travis ci build failure.   I think this is attempting to run the standard build from upstream.   I never do that, since we have our own build process driven from main.  I leave it to the reviewer to instruct me whether to worry about this failure or not.

**Comment by rabbah** [comment]
The upstream tests shouldn't fail but we should track/fix that separately.

**Comment by rabbah** [comment]
I noticed this was to `dev-date` branch instead of `dev` btw was that intentional (i thought we were normalizing on `dev` with tags).

**Comment by joshuaauerbachwatson** [comment]
The use of the dev-date branch was deliberate because at the tail end of the effort to switch over to using tags, we elected to defer regularizing the branch names.   In runtimes where a dev-date branch was active, the use of that branch was continued.

> (i thought we were normalizing on `dev` with tags).

Almost right.   It's the pronoun that it's question.   I thought _you_ would eventually want to normalize in that way.   I eschew any knowledge of or willingness to perform actions in github that extend beyond my comfort zone.   Resetting, renaming, force pushing, rebasing all have strict limits for me (I will do some of these things to private branches, never shared ones).

**Comment by rabbah** [comment]
Ha! OK I will do it now before I forget again.

**Comment by rabbah** [comment]
The dev branch has been synchronized with dev-date.

**Pull request merged**
